using ZAPI_OUTBOUND_DELIVERY_SRV1 from './external/ZAPI_OUTBOUND_DELIVERY_SRV1.cds';

service ZAPI_OUTBOUND_DELIVERY_SRV1SampleService {
    @readonly
    entity A_OutbDeliveryDocFlow as projection on ZAPI_OUTBOUND_DELIVERY_SRV1.A_OutbDeliveryDocFlow
    {        Deliveryversion, key PrecedingDocument, PrecedingDocumentCategory, key PrecedingDocumentItem, Subsequentdocument, QuantityInBaseUnit, SubsequentDocumentItem, SDFulfillmentCalculationRule, key SubsequentDocumentCategory, TransferOrderInWrhsMgmtIsConfd     }    
;
    @readonly
    entity A_OutbDeliveryItem as projection on ZAPI_OUTBOUND_DELIVERY_SRV1.A_OutbDeliveryItem
    {        ActualDeliveredQtyInBaseUnit, DeliveryVersion, ActualDeliveryQuantity, AdditionalCustomerGroup1, AdditionalCustomerGroup2, AdditionalCustomerGroup3, AdditionalCustomerGroup4, AdditionalCustomerGroup5, AdditionalMaterialGroup1, AdditionalMaterialGroup2, AdditionalMaterialGroup3, AdditionalMaterialGroup4, AdditionalMaterialGroup5, AlternateProductNumber, BaseUnit, Batch, BatchBySupplier, BatchClassification, BOMExplosion, BusinessArea, ConsumptionPosting, ControllingArea, CostCenter, CreatedByUser, CreationDate, CreationTime, CustEngineeringChgStatus, key DeliveryDocument, key DeliveryDocumentItem, DeliveryDocumentItemCategory, DeliveryDocumentItemText, DeliveryGroup, DeliveryQuantityUnit, DeliveryRelatedBillingStatus, DeliveryToBaseQuantityDnmntr, DeliveryToBaseQuantityNmrtr, DepartmentClassificationByCust, DistributionChannel, Division, FixedShipgProcgDurationInDays, GLAccount, GoodsMovementReasonCode, GoodsMovementStatus, GoodsMovementType, HigherLevelItem, InspectionLot, InspectionPartialLot, IntercompanyBillingStatus, InternationalArticleNumber, InventorySpecialStockType, InventoryValuationType, IsCompletelyDelivered, IsNotGoodsMovementsRelevant, IsSeparateValuation, IssgOrRcvgBatch, IssgOrRcvgMaterial, IssgOrRcvgSpclStockInd, IssgOrRcvgStockCategory, IssgOrRcvgValuationType, IssuingOrReceivingPlant, IssuingOrReceivingStorageLoc, ItemBillingBlockReason, ItemBillingIncompletionStatus, ItemDeliveryIncompletionStatus, ItemGdsMvtIncompletionSts, ItemGeneralIncompletionStatus, ItemGrossWeight, ItemIsBillingRelevant, ItemNetWeight, ItemPackingIncompletionStatus, ItemPickingIncompletionStatus, ItemVolume, ItemVolumeUnit, ItemWeightUnit, LastChangeDate, LoadingGroup, ManufactureDate, Material, MaterialByCustomer, MaterialFreightGroup, MaterialGroup, MaterialIsBatchManaged, MaterialIsIntBatchManaged, NumberOfSerialNumbers, OrderID, OrderItem, OriginalDeliveryQuantity, OriginallyRequestedMaterial, OverdelivTolrtdLmtRatioInPct, PackingStatus, PartialDeliveryIsAllowed, PaymentGuaranteeForm, PickingConfirmationStatus, PickingControl, PickingStatus, Plant, PrimaryPostingSwitch, ProductAvailabilityDate, ProductAvailabilityTime, ProductConfiguration, ProductHierarchyNode, ProfitabilitySegment, ProfitCenter, ProofOfDeliveryRelevanceCode, ProofOfDeliveryStatus, QuantityIsFixed, ReceivingPoint, ReferenceDocumentLogicalSystem, ReferenceSDDocument, ReferenceSDDocumentCategory, ReferenceSDDocumentItem, RetailPromotion, SalesDocumentItemType, SalesGroup, SalesOffice, SDDocumentCategory, SDProcessStatus, ShelfLifeExpirationDate, StatisticsDate, StockType, StorageBin, StorageLocation, StorageType, SubsequentMovementType, TransportationGroup, UnderdelivTolrtdLmtRatioInPct, UnlimitedOverdeliveryIsAllowed, VarblShipgProcgDurationInDays, Warehouse, WarehouseActivityStatus, WarehouseStagingArea, WarehouseStockCategory, WarehouseStorageBin     }    
;
    @readonly
    entity A_OutbDeliveryPartner as projection on ZAPI_OUTBOUND_DELIVERY_SRV1.A_OutbDeliveryPartner
    {        AddressID, ContactPerson, Customer, key PartnerFunction, Personnel, key SDDocument, SDDocumentItem, Supplier     }    
;
}